### ISSUE TITLE
Why http request does not processed when all threads are busy?

### ISSUE THREAD

**Issue by Axi-ua** [zeroabsolute/Node-Internals#1]
Hello,
I have read your artical about [thread pool](https://medium.com/softup-technologies/node-js-internals-not-everything-happens-on-the-thread-pool-a14d0a286efb) and have a question about it.

If http does not use thread pool, why it cant be processed when all threads are busy?
I have two examples: 
1:
`const crypto = require("crypto");
const https = require("https");

const start = Date.now();
function doCrypto() {
  crypto.pbkdf2("a", "b", 100000, 512, "sha512", function () {
    console.log("Crypto: " + (Date.now() - start));
  });
}

function doHTTP() {
  https
    .request("https://www.google.com", function (res) {
      res.on("data", function () {});
      res.on("end", function () {
        console.log("Request: " + (Date.now() - start));
      });
    })
    .end();
}

doHTTP();
doCrypto();
doCrypto();
doCrypto();
doCrypto();
`
Results:
Request: 330
Crypto: 694
Crypto: 703
Crypto: 731
Crypto: 740

2:
`const crypto = require("crypto");

const https = require("https");

const start = Date.now();
function doCrypto() {
  crypto.pbkdf2("a", "b", 100000, 512, "sha512", function () {
    console.log("Crypto: " + (Date.now() - start));
  });
}

function doHTTP() {
  https
    .request("https://www.google.com", function (res) {
      res.on("data", function () {});
      res.on("end", function () {
        console.log("Request: " + (Date.now() - start));
      });
    })
    .end();
}

doCrypto();
doCrypto();
doCrypto();
doCrypto();
doHTTP();
`
Results:
Crypto: 721
Crypto: 728
Crypto: 797
Crypto: 802
Request: 996

**Comment by zeroabsolute** [comment]
Hello @Axi-ua !
This is an expected behaviour actually. When you call `http.request()` with a domain instead of an IP address, Node will perform a `dns.lookup()` on the domain name first, then it will execute the request.
The `dns.lookup()` method is asynchronous with respect to user code, but it is actually executed on the thread pool. This is why you get those results when  you have blocked the thread pool with the crypto calls. On the "Conclusion" section on my article, I have included the link to [this](https://nodejs.org/api/dns.html#dns_implementation_considerations) paragraph, which explains the scenario in greater detail.

So, going back to your code, what you could do is:

- Use an online tool to resolve www.google.com manually and paste the IP address you get as an argument to the `http.request()`.
- Use `dns.resolve()` first to get the IP address for the given domain name (in this case you will not be affected by the blocked thread pool, since _resolve_ is a pure network call). Then, use that IP as an argument to your _request_ function.

Here I have slightly modified your second snippet to use _resolve_:
```
const crypto = require('crypto');
const http = require('http');
const dns = require('dns').promises;

const start = Date.now();

function doCrypto() {
  crypto.pbkdf2('a', 'b', 100000, 512, 'sha512', function () {
    console.log('Crypto: ' + (Date.now() - start));
  });
}

async function doHTTP() {
  const addresses = await dns.resolve4('www.google.com');

  http
    .request({ host: addresses[0] }, function (res) {
      res.on('data', function () { });
      res.on('end', function () {
        console.log('Request: ' + (Date.now() - start));
      });
    })
    .end();
}

doCrypto();
doCrypto();
doCrypto();
doCrypto();
doHTTP();
```

And I get these results on my device after executing both snippets (_note that the first snippet is untouched, so the request still utilises the thread pool_):
```
user@Users-MacBook-Pro ~/Desktop> node 1.js
Request: 376
Crypto: 718
Crypto: 723
Crypto: 729
Crypto: 790
user@Users-MacBook-Pro ~/Desktop> node 2.js
Request: 182
Crypto: 721
Crypto: 735
Crypto: 739
Crypto: 752
user@Users-MacBook-Pro ~/Desktop>
```

**Comment by Axi-ua** [comment]
Thank you very much for the explanation.
Now everything is clear.
